# Example config to store strategy parameters, scheduling, etc.

strategy:
  symbols: ["BTC-USDT-PERP", "ETH-USDT-PERP", "SOL-USDT-PERP"]
  candle_interval: "1h"
  lookback_momentum: 14
  lookback_rsi: 14
  top_n_momentum: 3
  fraction_of_balance_per_trade: 0.02  # 2% of free margin for each trade
  stop_loss_percent: 0.05             # 5% stop loss from entry
  take_profit_percent: 0.1            # 10% take profit from entry

schedule:
  run_interval_minutes: 60
